#!/bin/bash
# This script sets up the Go 1.24 tools system integration

set -e  # Exit on error

# Make sure we're in the root directory
cd "$(dirname "$0")"

echo "Setting up Go 1.24 tools system integration..."

# Create tools.go file
cat > tools.go << 'EOF'
//go:build tools
// +build tools

package tools

import (
	// Tools we depend on
	_ "github.com/tmc/mkprog/tools/mkprog-mkprog"
	_ "github.com/tmc/mkprog/tools/mkprog-quine"
	_ "github.com/tmc/mkprog/tools/list-tools"
	// Add other tools as needed
)
EOF

echo "Created tools.go"

# Create templates directory
mkdir -p templates

# Create self-introspection template
cat > templates/self_introspection.go.tmpl << 'EOF'
// Metadata represents program metadata stored in .mkprog.json
type Metadata struct {
    Name           string   `json:"name"`
    Description    string   `json:"description"`
    GeneratedBy    string   `json:"generated_by"`
    MkprogVersion  string   `json:"mkprog_version"`
    ToolsAvailable []string `json:"tools_available,omitempty"`
}

// Handle introspection flags and return true if one was processed
func handleIntrospectionFlags() bool {
    showPrompt := flag.Bool("show-prompt", false, "Output the prompt used to generate this program")
    showSource := flag.String("show-source", "", "Output source code (specify file or leave empty for file list)")
    showInfo := flag.Bool("mkprog-info", false, "Show information about the mkprog ecosystem")
    
    // Must be called after flag.Parse() in run()
    
    if *showPrompt {
        data, err := os.ReadFile("PROMPT.md")
        if err == nil {
            fmt.Println(string(data))
            return true
        }
        fmt.Println("Prompt file not found")
        return true
    }
    
    if *showSource != "" {
        data, err := os.ReadFile(*showSource)
        if err != nil {
            fmt.Fprintf(os.Stderr, "Error reading file: %v\n", err)
            return true
        }
        fmt.Println(string(data))
        return true
    } else if flag.Lookup("show-source").Value.String() == "" {
        files, _ := filepath.Glob("*.go")
        fmt.Println("Source files:")
        for _, f := range files {
            fmt.Println("  " + f)
        }
        return true
    }
    
    if *showInfo {
        data, err := os.ReadFile(".mkprog.json")
        var metadata Metadata
        if err == nil {
            if err := json.Unmarshal(data, &metadata); err == nil {
                fmt.Printf("Program: %s\nDescription: %s\nGenerated by: %s %s\n",
                    metadata.Name, metadata.Description, 
                    metadata.GeneratedBy, metadata.MkprogVersion)
                if len(metadata.ToolsAvailable) > 0 {
                    fmt.Println("\nRelated tools:")
                    for _, tool := range metadata.ToolsAvailable {
                        fmt.Println("  " + tool)
                    }
                }
                return true
            }
        }
        
        fmt.Println("This program was generated by mkprog")
        return true
    }
    
    return false
}
EOF

echo "Created templates/self_introspection.go.tmpl"

# Create SDK directory and package
mkdir -p sdk

# Create sdk package
cat > sdk/sdk.go << 'EOF'
// Package mkprogsdk provides utilities for programs generated by mkprog
package mkprogsdk

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
)

// Metadata represents program metadata stored in .mkprog.json
type Metadata struct {
	Name           string   `json:"name"`
	Description    string   `json:"description"`
	GeneratedBy    string   `json:"generated_by"`
	MkprogVersion  string   `json:"mkprog_version"`
	ToolsAvailable []string `json:"tools_available,omitempty"`
}

// ReadMetadata reads program metadata from .mkprog.json
func ReadMetadata() (Metadata, error) {
	var metadata Metadata
	data, err := os.ReadFile(".mkprog.json")
	if err != nil {
		return metadata, err
	}
	err = json.Unmarshal(data, &metadata)
	return metadata, err
}

// ShowPrompt displays the program's generation prompt
func ShowPrompt() error {
	data, err := os.ReadFile("PROMPT.md")
	if err != nil {
		return err
	}
	fmt.Println(string(data))
	return nil
}

// ShowSource displays source code or lists available files
func ShowSource(file string) error {
	if file == "" {
		// List all source files
		files, err := filepath.Glob("*.go")
		if err != nil {
			return err
		}
		fmt.Println("Source files:")
		for _, f := range files {
			fmt.Println("  " + f)
		}
		return nil
	}
	
	// Show specific file
	data, err := os.ReadFile(file)
	if err != nil {
		return err
	}
	fmt.Println(string(data))
	return nil
}

// ShowInfo displays information about the program and available tools
func ShowInfo() error {
	metadata, err := ReadMetadata()
	if err == nil {
		fmt.Printf("Program: %s\nDescription: %s\nGenerated by: %s %s\n",
			metadata.Name, metadata.Description,
			metadata.GeneratedBy, metadata.MkprogVersion)
		
		if len(metadata.ToolsAvailable) > 0 {
			fmt.Println("\nRelated tools:")
			for _, tool := range metadata.ToolsAvailable {
				fmt.Println("  " + tool)
			}
		}
		return nil
	}
	
	fmt.Println("This program was generated by mkprog")
	return nil
}
EOF

echo "Created sdk/sdk.go"

# Update main.go to use the template and SDK
echo "To complete setup:"
echo "1. Update main.go to embed and use the template"
echo "2. Run 'go mod tidy' to update dependencies"
echo "3. Update system-prompt.txt to reference the SDK"

echo "Setup complete!"
chmod +x setup-tools-system.sh