package generator

import (
	"fmt"
	"strings"
	"time"

	"github.com/iancoleman/strcase"
)

// GenerateGo generates Go structs for the given schema
func GenerateGo(schema *Schema, dbType string) (string, error) {
	var b strings.Builder

	// Header
	b.WriteString("// Code generated by schemagen; DO NOT EDIT.\n")
	b.WriteString(fmt.Sprintf("// Generated at: %s\n\n", time.Now().Format(time.RFC3339)))
	b.WriteString("package models\n\n")

	// Imports
	imports := make(map[string]bool)
	imports["time"] = false

	for _, table := range schema.Tables {
		for _, col := range table.Columns {
			// Check for time imports
			if col.Type == TypeTimestamp || col.Type == TypeDate || col.Type == TypeTime {
				imports["time"] = true
			}

			// Check for UUID imports
			if col.Type == TypeUUID {
				imports["github.com/google/uuid"] = true
			}
		}
	}

	if len(imports) > 0 {
		b.WriteString("import (\n")
		for imp, used := range imports {
			if used {
				b.WriteString(fmt.Sprintf("\t\"%s\"\n", imp))
			}
		}
		b.WriteString(")\n\n")
	}

	// Generate structs for each table
	for _, table := range schema.Tables {
		structName := strcase.ToCamel(table.Name)
		
		// Add table comment if present
		if table.Comment != "" {
			b.WriteString(fmt.Sprintf("// %s %s\n", structName, table.Comment))
		} else {
			b.WriteString(fmt.Sprintf("// %s represents the %s table.\n", structName, table.Name))
		}
		
		b.WriteString(fmt.Sprintf("type %s struct {\n", structName))

		// Generate struct fields
		for _, col := range table.Columns {
			fieldName := strcase.ToCamel(col.Name)
			goType := goDataType(col)
			
			// Generate field tags
			tags := generateTags(col, table.Name, dbType)
			
			// Add comment if present
			if col.Comment != "" {
				b.WriteString(fmt.Sprintf("\t// %s %s\n", fieldName, col.Comment))
			}
			
			// Make nullable fields pointers
			if col.Nullable && goType != "interface{}" {
				goType = "*" + goType
			}
			
			b.WriteString(fmt.Sprintf("\t%s %s %s\n", fieldName, goType, tags))
		}
		
		b.WriteString("}\n\n")

		// Add table name method
		b.WriteString(fmt.Sprintf("// TableName returns the name of the %s table.\n", table.Name))
		b.WriteString(fmt.Sprintf("func (%s) TableName() string {\n", structName[0:1]))
		b.WriteString(fmt.Sprintf("\treturn \"%s\"\n", table.Name))
		b.WriteString("}\n\n")
	}

	return b.String(), nil
}

// goDataType maps schema types to Go data types
func goDataType(col *Column) string {
	switch col.Type {
	case TypeInteger, TypeSmallInt:
		return "int"
	case TypeBigInt:
		return "int64"
	case TypeText, TypeVarchar, TypeChar:
		return "string"
	case TypeBool:
		return "bool"
	case TypeFloat:
		return "float64"
	case TypeNumeric:
		if col.Precision > 0 && col.Scale > 0 {
			return "float64"
		}
		return "int64"
	case TypeDate, TypeTime, TypeTimestamp:
		return "time.Time"
	case TypeUUID:
		return "uuid.UUID"
	case TypeJSON, TypeJSONB:
		return "interface{}"
	case TypeBLOB:
		return "[]byte"
	default:
		return "string"
	}
}

// generateTags generates struct tags for the given column
func generateTags(col *Column, tableName string, dbType string) string {
	var tags []string

	// JSON tag
	jsonTag := fmt.Sprintf("json:\"%s\"", col.Name)
	tags = append(tags, jsonTag)

	// DB tag based on the database type
	switch dbType {
	case "postgres", "postgresql":
		dbTag := generatePostgresTag(col, tableName)
		tags = append(tags, dbTag)
	case "mysql":
		dbTag := generateMySQLTag(col, tableName)
		tags = append(tags, dbTag)
	case "sqlite":
		dbTag := generateSQLiteTag(col, tableName)
		tags = append(tags, dbTag)
	}

	// GORM tags
	gormTag := generateGORMTag(col)
	if gormTag != "" {
		tags = append(tags, gormTag)
	}

	// Validation tags
	validationTag := generateValidationTag(col)
	if validationTag != "" {
		tags = append(tags, validationTag)
	}

	return fmt.Sprintf("`%s`", strings.Join(tags, " "))
}

// generatePostgresTag generates PostgreSQL-specific tags
func generatePostgresTag(col *Column, tableName string) string {
	var tagParts []string

	tagParts = append(tagParts, fmt.Sprintf("column:%s", col.Name))

	if col.PrimaryKey {
		tagParts = append(tagParts, "primaryKey")
	}

	if col.AutoIncrement {
		tagParts = append(tagParts, "autoIncrement")
	}

	if col.Default != "" {
		tagParts = append(tagParts, fmt.Sprintf("default:%s", col.Default))
	}

	if !col.Nullable {
		tagParts = append(tagParts, "not null")
	}

	if col.Unique {
		tagParts = append(tagParts, "unique")
	}

	if col.Type == TypeVarchar && col.Length > 0 {
		tagParts = append(tagParts, fmt.Sprintf("size:%d", col.Length))
	}

	if col.References != "" {
		tagParts = append(tagParts, fmt.Sprintf("foreignKey:%s", col.References))
	}

	return fmt.Sprintf("pg:\"%s\"", strings.Join(tagParts, ";"))
}

// generateMySQLTag generates MySQL-specific tags
func generateMySQLTag(col *Column, tableName string) string {
	var tagParts []string

	tagParts = append(tagParts, fmt.Sprintf("column:%s", col.Name))

	if col.PrimaryKey {
		tagParts = append(tagParts, "primaryKey")
	}

	if col.AutoIncrement {
		tagParts = append(tagParts, "autoIncrement")
	}

	if col.Default != "" {
		tagParts = append(tagParts, fmt.Sprintf("default:%s", col.Default))
	}

	if !col.Nullable {
		tagParts = append(tagParts, "not null")
	}

	if col.Unique {
		tagParts = append(tagParts, "unique")
	}

	if col.Type == TypeVarchar && col.Length > 0 {
		tagParts = append(tagParts, fmt.Sprintf("size:%d", col.Length))
	}

	if col.References != "" {
		tagParts = append(tagParts, fmt.Sprintf("foreignKey:%s", col.References))
	}

	return fmt.Sprintf("gorm:\"%s\"", strings.Join(tagParts, ";"))
}

// generateSQLiteTag generates SQLite-specific tags
func generateSQLiteTag(col *Column, tableName string) string {
	var tagParts []string

	tagParts = append(tagParts, fmt.Sprintf("column:%s", col.Name))

	if col.PrimaryKey {
		tagParts = append(tagParts, "primaryKey")
	}

	if col.AutoIncrement {
		tagParts = append(tagParts, "autoIncrement")
	}

	if col.Default != "" {
		tagParts = append(tagParts, fmt.Sprintf("default:%s", col.Default))
	}

	if !col.Nullable {
		tagParts = append(tagParts, "not null")
	}

	if col.Unique {
		tagParts = append(tagParts, "unique")
	}

	if col.References != "" {
		tagParts = append(tagParts, fmt.Sprintf("foreignKey:%s", col.References))
	}

	return fmt.Sprintf("sqlite:\"%s\"", strings.Join(tagParts, ";"))
}

// generateGORMTag generates GORM ORM tags
func generateGORMTag(col *Column) string {
	var tagParts []string

	tagParts = append(tagParts, fmt.Sprintf("column:%s", col.Name))

	if col.PrimaryKey {
		tagParts = append(tagParts, "primaryKey")
	}

	if col.AutoIncrement {
		tagParts = append(tagParts, "autoIncrement")
	}

	if col.Default != "" {
		tagParts = append(tagParts, fmt.Sprintf("default:%s", col.Default))
	}

	if !col.Nullable {
		tagParts = append(tagParts, "not null")
	}

	if col.Unique {
		tagParts = append(tagParts, "unique")
	}

	if col.Type == TypeVarchar && col.Length > 0 {
		tagParts = append(tagParts, fmt.Sprintf("size:%d", col.Length))
	}

	if col.References != "" {
		refParts := strings.Split(col.References, ".")
		if len(refParts) == 2 {
			tagParts = append(tagParts, fmt.Sprintf("references:%s(%s)", refParts[0], refParts[1]))
		}
	}

	if col.OnDelete != "" {
		tagParts = append(tagParts, fmt.Sprintf("onDelete:%s", col.OnDelete))
	}

	if col.OnUpdate != "" {
		tagParts = append(tagParts, fmt.Sprintf("onUpdate:%s", col.OnUpdate))
	}

	return fmt.Sprintf("gorm:\"%s\"", strings.Join(tagParts, ";"))
}

// generateValidationTag generates validation tags
func generateValidationTag(col *Column) string {
	var validations []string

	if !col.Nullable && col.Type != TypeBool {
		validations = append(validations, "required")
	}

	if col.Unique {
		validations = append(validations, "unique")
	}

	if col.Type == TypeVarchar && col.Length > 0 {
		validations = append(validations, fmt.Sprintf("max=%d", col.Length))
	}

	if col.Type == TypeEmail {
		validations = append(validations, "email")
	}

	if len(validations) > 0 {
		return fmt.Sprintf("validate:\"%s\"", strings.Join(validations, ","))
	}

	return ""
}