package generator

import (
	"fmt"
	"strings"
)

// GenerateSQL generates SQL for the given schema and database type
func GenerateSQL(schema *Schema, dbType string) (string, error) {
	switch dbType {
	case "postgres", "postgresql":
		return generatePostgresSQL(schema)
	case "mysql":
		return generateMySQLSQL(schema)
	case "sqlite":
		return generateSQLiteSQL(schema)
	default:
		return "", fmt.Errorf("unsupported database type: %s", dbType)
	}
}

// generatePostgresSQL generates PostgreSQL schema SQL
func generatePostgresSQL(schema *Schema) (string, error) {
	var b strings.Builder

	b.WriteString("-- Generated by schemagen\n\n")

	// Create tables
	for _, table := range schema.Tables {
		b.WriteString(fmt.Sprintf("CREATE TABLE %s (\n", table.Name))

		// Columns
		columns := make([]string, 0, len(table.Columns))
		for _, col := range table.Columns {
			colDef := fmt.Sprintf("  %s %s", col.Name, postgresDataType(col))

			if col.PrimaryKey {
				colDef += " PRIMARY KEY"
			}
			if col.Unique {
				colDef += " UNIQUE"
			}
			if !col.Nullable {
				colDef += " NOT NULL"
			}
			if col.Default != "" {
				colDef += fmt.Sprintf(" DEFAULT %s", col.Default)
			}
			if col.AutoIncrement {
				// In PostgreSQL, we typically use SERIAL types for auto-increment
				colDef = fmt.Sprintf("  %s SERIAL", col.Name)
				if col.PrimaryKey {
					colDef += " PRIMARY KEY"
				}
			}

			columns = append(columns, colDef)
		}

		// Foreign keys
		for _, col := range table.Columns {
			if col.References != "" {
				fkDef := fmt.Sprintf("  FOREIGN KEY (%s) REFERENCES %s", col.Name, col.References)
				if col.OnDelete != "" {
					fkDef += fmt.Sprintf(" ON DELETE %s", col.OnDelete)
				}
				if col.OnUpdate != "" {
					fkDef += fmt.Sprintf(" ON UPDATE %s", col.OnUpdate)
				}
				columns = append(columns, fkDef)
			}
		}

		b.WriteString(strings.Join(columns, ",\n"))
		b.WriteString("\n);\n\n")

		// Create indexes
		for _, idx := range table.Indexes {
			idxType := "INDEX"
			if idx.Unique {
				idxType = "UNIQUE INDEX"
			}

			method := ""
			if idx.Method != "" {
				method = fmt.Sprintf(" USING %s", idx.Method)
			}

			includes := ""
			if len(idx.Includes) > 0 {
				includes = fmt.Sprintf(" INCLUDE (%s)", strings.Join(idx.Includes, ", "))
			}

			b.WriteString(fmt.Sprintf("CREATE %s %s ON %s%s (%s)%s;\n",
				idxType, idx.Name, table.Name, method, strings.Join(idx.Columns, ", "), includes))
		}

		// Add comments if present
		if table.Comment != "" {
			b.WriteString(fmt.Sprintf("COMMENT ON TABLE %s IS '%s';\n",
				table.Name, escapeSQL(table.Comment)))
		}

		for _, col := range table.Columns {
			if col.Comment != "" {
				b.WriteString(fmt.Sprintf("COMMENT ON COLUMN %s.%s IS '%s';\n",
					table.Name, col.Name, escapeSQL(col.Comment)))
			}
		}

		b.WriteString("\n")
	}

	return b.String(), nil
}

// generateMySQLSQL generates MySQL schema SQL
func generateMySQLSQL(schema *Schema) (string, error) {
	var b strings.Builder

	b.WriteString("-- Generated by schemagen\n\n")

	// Create tables
	for _, table := range schema.Tables {
		b.WriteString(fmt.Sprintf("CREATE TABLE `%s` (\n", table.Name))

		// Columns
		columns := make([]string, 0, len(table.Columns))
		primaryKeys := make([]string, 0)

		for _, col := range table.Columns {
			colDef := fmt.Sprintf("  `%s` %s", col.Name, mysqlDataType(col))

			if !col.Nullable {
				colDef += " NOT NULL"
			}
			if col.Default != "" {
				colDef += fmt.Sprintf(" DEFAULT %s", col.Default)
			}
			if col.AutoIncrement {
				colDef += " AUTO_INCREMENT"
			}
			if col.Comment != "" {
				colDef += fmt.Sprintf(" COMMENT '%s'", escapeSQL(col.Comment))
			}

			columns = append(columns, colDef)

			// Collect primary keys
			if col.PrimaryKey {
				primaryKeys = append(primaryKeys, col.Name)
			}
		}

		// Add primary key constraint if needed
		if len(primaryKeys) > 0 {
			pkDef := fmt.Sprintf("  PRIMARY KEY (`%s`)", strings.Join(primaryKeys, "`, `"))
			columns = append(columns, pkDef)
		}

		// Add unique constraints
		for _, col := range table.Columns {
			if col.Unique && !col.PrimaryKey {
				columns = append(columns, fmt.Sprintf("  UNIQUE KEY `%s_unique` (`%s`)", col.Name, col.Name))
			}
		}

		// Foreign keys
		for _, col := range table.Columns {
			if col.References != "" {
				// Parse the reference (table.column)
				refParts := strings.Split(col.References, ".")
				if len(refParts) != 2 {
					continue
				}
				refTable := refParts[0]
				refCol := refParts[1]

				fkName := fmt.Sprintf("fk_%s_%s", table.Name, col.Name)
				fkDef := fmt.Sprintf("  CONSTRAINT `%s` FOREIGN KEY (`%s`) REFERENCES `%s` (`%s`)",
					fkName, col.Name, refTable, refCol)

				if col.OnDelete != "" {
					fkDef += fmt.Sprintf(" ON DELETE %s", col.OnDelete)
				}
				if col.OnUpdate != "" {
					fkDef += fmt.Sprintf(" ON UPDATE %s", col.OnUpdate)
				}
				columns = append(columns, fkDef)
			}
		}

		b.WriteString(strings.Join(columns, ",\n"))

		// Table options
		engine := "InnoDB"
		charset := "utf8mb4"
		collate := "utf8mb4_unicode_ci"
		
		if props := table.Properties; props != nil {
			if e, ok := props["engine"]; ok {
				engine = e
			}
			if c, ok := props["charset"]; ok {
				charset = c
			}
			if coll, ok := props["collate"]; ok {
				collate = coll
			}
		}

		comment := ""
		if table.Comment != "" {
			comment = fmt.Sprintf(" COMMENT='%s'", escapeSQL(table.Comment))
		}

		b.WriteString(fmt.Sprintf("\n) ENGINE=%s DEFAULT CHARSET=%s COLLATE=%s%s;\n\n",
			engine, charset, collate, comment))

		// Create indexes
		for _, idx := range table.Indexes {
			idxType := "INDEX"
			if idx.Unique {
				idxType = "UNIQUE INDEX"
			}

			b.WriteString(fmt.Sprintf("CREATE %s `%s` ON `%s` (`%s`);\n",
				idxType, idx.Name, table.Name, strings.Join(idx.Columns, "`, `")))
		}

		b.WriteString("\n")
	}

	return b.String(), nil
}

// generateSQLiteSQL generates SQLite schema SQL
func generateSQLiteSQL(schema *Schema) (string, error) {
	var b strings.Builder

	b.WriteString("-- Generated by schemagen\n\n")

	// Create tables
	for _, table := range schema.Tables {
		b.WriteString(fmt.Sprintf("CREATE TABLE %s (\n", table.Name))

		// Columns
		columns := make([]string, 0, len(table.Columns))
		for _, col := range table.Columns {
			colDef := fmt.Sprintf("  %s %s", col.Name, sqliteDataType(col))

			if col.PrimaryKey {
				colDef += " PRIMARY KEY"
				if col.AutoIncrement {
					colDef += " AUTOINCREMENT"
				}
			}
			if !col.Nullable {
				colDef += " NOT NULL"
			}
			if col.Unique && !col.PrimaryKey {
				colDef += " UNIQUE"
			}
			if col.Default != "" {
				colDef += fmt.Sprintf(" DEFAULT %s", col.Default)
			}

			columns = append(columns, colDef)
		}

		// Foreign keys
		for _, col := range table.Columns {
			if col.References != "" {
				fkDef := fmt.Sprintf("  FOREIGN KEY (%s) REFERENCES %s", col.Name, col.References)
				if col.OnDelete != "" {
					fkDef += fmt.Sprintf(" ON DELETE %s", col.OnDelete)
				}
				if col.OnUpdate != "" {
					fkDef += fmt.Sprintf(" ON UPDATE %s", col.OnUpdate)
				}
				columns = append(columns, fkDef)
			}
		}

		b.WriteString(strings.Join(columns, ",\n"))
		b.WriteString("\n);\n\n")

		// Create indexes
		for _, idx := range table.Indexes {
			idxType := ""
			if idx.Unique {
				idxType = "UNIQUE "
			}

			b.WriteString(fmt.Sprintf("CREATE %sINDEX %s ON %s (%s);\n",
				idxType, idx.Name, table.Name, strings.Join(idx.Columns, ", ")))
		}

		b.WriteString("\n")
	}

	return b.String(), nil
}

// postgresDataType maps schema types to PostgreSQL data types
func postgresDataType(col *Column) string {
	switch col.Type {
	case TypeInteger:
		return "INTEGER"
	case TypeSmallInt:
		return "SMALLINT"
	case TypeBigInt:
		return "BIGINT"
	case TypeText:
		return "TEXT"
	case TypeVarchar:
		if col.Length > 0 {
			return fmt.Sprintf("VARCHAR(%d)", col.Length)
		}
		return "VARCHAR"
	case TypeChar:
		if col.Length > 0 {
			return fmt.Sprintf("CHAR(%d)", col.Length)
		}
		return "CHAR"
	case TypeBool:
		return "BOOLEAN"
	case TypeFloat:
		return "FLOAT"
	case TypeNumeric:
		if col.Precision > 0 && col.Scale > 0 {
			return fmt.Sprintf("NUMERIC(%d,%d)", col.Precision, col.Scale)
		} else if col.Precision > 0 {
			return fmt.Sprintf("NUMERIC(%d)", col.Precision)
		}
		return "NUMERIC"
	case TypeDate:
		return "DATE"
	case TypeTime:
		return "TIME"
	case TypeTimestamp:
		return "TIMESTAMP"
	case TypeUUID:
		return "UUID"
	case TypeJSON:
		return "JSON"
	case TypeJSONB:
		return "JSONB"
	default:
		return string(col.Type)
	}
}

// mysqlDataType maps schema types to MySQL data types
func mysqlDataType(col *Column) string {
	switch col.Type {
	case TypeInteger:
		return "INT"
	case TypeSmallInt:
		return "SMALLINT"
	case TypeBigInt:
		return "BIGINT"
	case TypeText:
		return "TEXT"
	case TypeVarchar:
		if col.Length > 0 {
			return fmt.Sprintf("VARCHAR(%d)", col.Length)
		}
		return "VARCHAR(255)"
	case TypeChar:
		if col.Length > 0 {
			return fmt.Sprintf("CHAR(%d)", col.Length)
		}
		return "CHAR(1)"
	case TypeBool:
		return "TINYINT(1)"
	case TypeFloat:
		return "FLOAT"
	case TypeNumeric:
		if col.Precision > 0 && col.Scale > 0 {
			return fmt.Sprintf("DECIMAL(%d,%d)", col.Precision, col.Scale)
		} else if col.Precision > 0 {
			return fmt.Sprintf("DECIMAL(%d)", col.Precision)
		}
		return "DECIMAL(10,2)"
	case TypeDate:
		return "DATE"
	case TypeTime:
		return "TIME"
	case TypeTimestamp:
		return "TIMESTAMP"
	case TypeUUID:
		return "CHAR(36)"
	case TypeJSON:
		return "JSON"
	case TypeBLOB:
		return "BLOB"
	default:
		return string(col.Type)
	}
}

// sqliteDataType maps schema types to SQLite data types
func sqliteDataType(col *Column) string {
	switch col.Type {
	case TypeInteger, TypeSmallInt, TypeBigInt:
		return "INTEGER"
	case TypeText, TypeVarchar, TypeChar:
		return "TEXT"
	case TypeBool:
		return "INTEGER"
	case TypeFloat, TypeNumeric:
		return "REAL"
	case TypeDate, TypeTime, TypeTimestamp:
		return "TEXT"
	case TypeBLOB:
		return "BLOB"
	default:
		return "TEXT"
	}
}

// escapeSQL escapes single quotes in SQL strings
func escapeSQL(s string) string {
	return strings.ReplaceAll(s, "'", "''")
}